# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuring-automatically-generated-release-notes

changelog:
  categories:
    - title: 💥 Breaking Changes
      labels:
        - "Type: Breaking change"

    - title: 🚀 New Features
      labels:
        - "Type: Feature"
        - "New data source"
        - "New resource"

    - title: 🐛 Bugfixes
      labels:
        - "Type: Bug"

    - title: 🪦 Deprecations
      labels:
        - "Deprecation"

    - title: 🛠️ Maintenance
      labels:
        - "Type: Maintenance"
        - "dependencies"

    - title: 📝 Documentation
      labels:
        - "Type: Documentation"

    - title: 🏷 Other Changes
      labels:
        - "*"
