version: "2"

run:
  allow-serial-runners: true

linters:
  default: none

  enable:
    - copyloopvar
    - durationcheck
    - errcheck
    - errname
    - errorlint
    # - forcetypeassert TODO: Re-enable when we can fix the issues
    - godot
    - govet
    - ineffassign
    - makezero
    - misspell
    - modernize
    - nilerr
    - nilnesserr # https://golangci-lint.run/docs/linters/configuration/#nilnesserr
    - predeclared
    - staticcheck
    - unconvert
    - unparam
    - unused
    - usetesting
    - tfproviderlint

  settings:
    custom:
      tfproviderlint:
        type: module
        description: Reports Terraform provider linting issues.
        original-url: github.com/bflad/tfproviderlint/cmd/tfproviderlintx
        settings:
          # https://github.com/bflad/tfproviderlint/tree/main?tab=readme-ov-file#standard-acceptance-test-checks
          enabled-checks:
            - AT005 # https://github.com/bflad/tfproviderlint/tree/main/passes/AT005
            - AT008 # https://github.com/bflad/tfproviderlint/tree/main/passes/AT008
            # - AT009 # https://github.com/bflad/tfproviderlint/tree/main/passes/AT009 # TODO: Enable when we can fix the issues
            # - R002 # https://github.com/bflad/tfproviderlint/tree/main/passes/R002
            # - R004 # https://github.com/bflad/tfproviderlint/tree/main/passes/R004
            - R005 # https://github.com/bflad/tfproviderlint/tree/main/passes/R005
            - R006 # https://github.com/bflad/tfproviderlint/tree/main/passes/R006
            # - R009 # https://github.com/bflad/tfproviderlint/tree/main/passes/R009 # TODO: Enable when we can fix the issues
            # - R010 # https://github.com/bflad/tfproviderlint/tree/main/passes/R010 # TODO: Enable when we can fix the issues
            - R011 # https://github.com/bflad/tfproviderlint/tree/main/passes/R011
            - R012 # https://github.com/bflad/tfproviderlint/tree/main/passes/R012
            - R013 # https://github.com/bflad/tfproviderlint/tree/main/passes/R013
            - R015 # https://github.com/bflad/tfproviderlint/tree/main/passes/R015
            - R016 # https://github.com/bflad/tfproviderlint/tree/main/passes/R016
            - R017 # https://github.com/bflad/tfproviderlint/tree/main/passes/R017
            # - R018 # https://github.com/bflad/tfproviderlint/tree/main/passes/R018 # TODO: Enable when we can fix the issues
            - S001 # https://github.com/bflad/tfproviderlint/tree/main/passes/S001
            - S002 # https://github.com/bflad/tfproviderlint/tree/main/passes/S002
            - S003 # https://github.com/bflad/tfproviderlint/tree/main/passes/S003
            - S004 # https://github.com/bflad/tfproviderlint/tree/main/passes/S004
            - S005 # https://github.com/bflad/tfproviderlint/tree/main/passes/S005
            # - S006 # https://github.com/bflad/tfproviderlint/tree/main/passes/S006 # TODO: Enable when we can fix the issues
            - S007 # https://github.com/bflad/tfproviderlint/tree/main/passes/S007
            - S008 # https://github.com/bflad/tfproviderlint/tree/main/passes/S008
            - S009 # https://github.com/bflad/tfproviderlint/tree/main/passes/S009
            - S010 # https://github.com/bflad/tfproviderlint/tree/main/passes/S010
            - S011 # https://github.com/bflad/tfproviderlint/tree/main/passes/S011
            - S012 # https://github.com/bflad/tfproviderlint/tree/main/passes/S012
            # - S013 # https://github.com/bflad/tfproviderlint/tree/main/passes/S013 # TODO: Enable when we can fix the issues
            - S014 # https://github.com/bflad/tfproviderlint/tree/main/passes/S014
            - S015 # https://github.com/bflad/tfproviderlint/tree/main/passes/S015
            - S016 # https://github.com/bflad/tfproviderlint/tree/main/passes/S016
            - S017 # https://github.com/bflad/tfproviderlint/tree/main/passes/S017
            - S018 # https://github.com/bflad/tfproviderlint/tree/main/passes/S018
            # - S019 # https://github.com/bflad/tfproviderlint/tree/main/passes/S019 # TODO: Enable when we can fix the issues
            # - S020 # https://github.com/bflad/tfproviderlint/tree/main/passes/S020 # TODO: Enable when we can fix the issues
            - S021 # https://github.com/bflad/tfproviderlint/tree/main/passes/S021
            - S022 # https://github.com/bflad/tfproviderlint/tree/main/passes/S022
            - S023 # https://github.com/bflad/tfproviderlint/tree/main/passes/S023
            - S024 # https://github.com/bflad/tfproviderlint/tree/main/passes/S024
            - S025 # https://github.com/bflad/tfproviderlint/tree/main/passes/S025
            - S026 # https://github.com/bflad/tfproviderlint/tree/main/passes/S026
            - S027 # https://github.com/bflad/tfproviderlint/tree/main/passes/S027
            - S028 # https://github.com/bflad/tfproviderlint/tree/main/passes/S028
            - S029 # https://github.com/bflad/tfproviderlint/tree/main/passes/S029
            - S030 # https://github.com/bflad/tfproviderlint/tree/main/passes/S030
            - S031 # https://github.com/bflad/tfproviderlint/tree/main/passes/S031
            - S032 # https://github.com/bflad/tfproviderlint/tree/main/passes/S032
            - S033 # https://github.com/bflad/tfproviderlint/tree/main/passes/S033
            - S035 # https://github.com/bflad/tfproviderlint/tree/main/passes/S035
            - S036 # https://github.com/bflad/tfproviderlint/tree/main/passes/S036
            - S037 # https://github.com/bflad/tfproviderlint/tree/main/passes/S037
            # - XR002 # https://github.com/bflad/tfproviderlint/tree/main/passes/XR002 # TODO: Enable when we can fix the issues
            # - XR003 # https://github.com/bflad/tfproviderlint/tree/main/passes/XR003 # TODO: Enable when we can fix the issues
            - XR004 # https://github.com/bflad/tfproviderlint/tree/main/passes/XR004
            # - XR005 # https://github.com/bflad/tfproviderlint/tree/main/passes/XR005 # TODO: Enable when we can fix the issues
            - XR006 # https://github.com/bflad/tfproviderlint/tree/main/passes/XR006
            # - XR007 # https://github.com/bflad/tfproviderlint/tree/main/passes/XR007 # TODO: Enable when we can fix the issues
            - XR008 # https://github.com/bflad/tfproviderlint/tree/main/passes/XR008
            # - XS001 # https://github.com/bflad/tfproviderlint/tree/main/passes/XS001 # TODO: Enable when we can fix the issues

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      - path: _test\.go
        linters:
          - unparam
        text: always receives
      - linters:
          - staticcheck
        text: "SA1019.*ByID.*deprecated"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports

  settings:
    gofmt:
      simplify: true
      rewrite-rules:
        - pattern: interface{}
          replacement: any
        - pattern: a[b:len(a)]
          replacement: a[b:]
    gofumpt:
      module-path: github.com/integrations/terraform-provider-github
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/integrations/terraform-provider-github

  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
