name: Bug
description: Report a bug or issue
title: "[BUG]: "
labels: ["Type: Bug", "Status: Triage"]
body:
  - type: markdown
    attributes:
      value: |
        Hi there,
        Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true


  - type: textarea
    id: terraform-version
    attributes:
      label: Terraform Version
      description: Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.
      placeholder: |
        Terraform v1.2.3
        on linux_amd64
        + provider registry.terraform.io/integrations/github v5.32.0
    validations:
      required: true

  - type: textarea
    id: affected-resources
    attributes:
      label: Affected Resource(s)
      description: |
        Please list the resources as a list. If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.
      placeholder: |
         - github_repository
         - github_branch_protection
    validations:
      required: true

  - type: textarea
    id: terraform-configuration-files
    attributes:
      label: Terraform Configuration Files
      render: hcl
      description: |
        Please copy and paste any relevant configration files. This will be automatically formatted into code, so no need for backticks.
        Please check your configuration before submission to ensure sensitive information is redacted.
    validations:
      required: false

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Please list the steps required to reproduce the issue.
      placeholder: |
        ```
        $ terraform apply
        ```
    validations:
      required: false

  - type: textarea
    id: debug-output
    attributes:
      label: Debug Output
      description: |
        Please copy and paste any relevant debug output. This will be automatically formatted into code, so no need for backticks.
        Please check your logs before submission to ensure sensitive information is redacted.
      render: shell
    validations:
      required: false

  - type: textarea
    id: panic-output
    attributes:
      label: Panic Output
      description: |
        Please copy and paste any relevant panic output. This will be automatically formatted into code, so no need for backticks.
        Please check your logs before submission to ensure sensitive information is redacted.
      render: shell
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/integrations/terraform-provider-github/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
