name: Add PRs & Issues to Octokit Org Project

on:
  issues:
    types: [reopened, opened]
  pull_request_target:
    types: [reopened, opened]

permissions: read-all

jobs:
  add-to-project:
    name: Add to Project
    runs-on: ubuntu-latest
    continue-on-error: true
    defaults:
      run:
        shell: bash
    steps:
      - name: Add to project
        uses: actions/add-to-project@244f685bbc3b7adfa8466e08b698b5577571133e # v1.0.2
        with:
          project-url: https://github.com/orgs/octokit/projects/10
          github-token: ${{ secrets.OCTOKITBOT_PROJECT_ACTION_TOKEN }}
          labeled: "Status: Stale"
          label-operator: NOT
