name: Issue/PR Response

on:
  issues:
    types:
      - opened
  pull_request_target:
    types:
      - opened

permissions: read-all

jobs:
  # ──────────────────────────────────────────────
  # PR Response
  # ──────────────────────────────────────────────
  respond-to-pr:
    name: Respond to PR
    if: >
      github.event_name == 'pull_request_target' &&
      github.actor != 'dependabot[bot]' &&
      github.actor != 'renovate[bot]' &&
      github.actor != 'github-actions[bot]' &&
      github.actor != 'octokitbot' &&
      github.repository == 'integrations/terraform-provider-github'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Comment on PR
        uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5.0.0
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            👋 Hi, and thank you for this contribution!

            This repo is maintained by GitHub and community members on a best-effort basis. We'll get to this as soon as we can.

            In the meantime, you're part of this community too: feel free to comment on, add to, or pick up any issues/PRs labeled `Status: Up for grabs`. Contributors like you are the reason this provider works. Happy coding! 🚀

            ---
            <sub>🤖 This is an automated message.</sub>

  # ──────────────────────────────────────────────
  # Issue Response
  # ──────────────────────────────────────────────
  respond-to-issue:
    name: Respond to Issue
    if: >
      github.event_name == 'issues' &&
      github.actor != 'dependabot[bot]' &&
      github.actor != 'renovate[bot]' &&
      github.actor != 'github-actions[bot]' &&
      github.actor != 'octokitbot' &&
      github.repository == 'integrations/terraform-provider-github'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Comment on issue
        uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5.0.0
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            👋 Hi, and thank you for opening this issue!

            This repo is maintained by GitHub and community members on a best-effort basis. We'll get to this as soon as we can.

            In the meantime, you're part of this community too: feel free to comment on, add to, or pick up any issues/PRs labeled `Status: Up for grabs`. Contributors like you are the reason this provider works. Happy coding! 🚀

            ---
            <sub>🤖 This is an automated message.</sub>
