name: Release

# This GitHub action creates a release when a tag that matches the pattern
# "v*" (e.g. v0.1.0) is created.
on:
  push:
    tags:
      - v*

concurrency:
  group: release
  cancel-in-progress: false

permissions: read-all

jobs:
  pre-release-tests:
    name: Run tests before release
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      TEST_STACKS_DIRECTORY: test_tf_stacks # root directory for test stacks
      PRE_RELEASE_TESTS: provider_only # directory name for pre-release tests
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Setup Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version-file: go.mod
          cache: true

      - name: Build provider
        run: go build -o terraform-provider-github

      - name: Setup dev overrides
        run: |
          ROOT_DIR=$(pwd)
          cat > ~/.terraformrc << EOF
          provider_installation {
            dev_overrides {
              "integrations/github" = "${ROOT_DIR}"
            }
            direct {}
          }
          EOF

      - name: Verify dev overrides setup
        run: cat ~/.terraformrc

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: 1.x

      - name: Check Terraform version
        run: terraform version

      - name: Terraform init
        continue-on-error: true # continue even if init fails
        run: terraform -chdir=./${{ env.TEST_STACKS_DIRECTORY }}/${{ env.PRE_RELEASE_TESTS }} init

      - name: Terraform validate
        run: terraform -chdir=./${{ env.TEST_STACKS_DIRECTORY }}/${{ env.PRE_RELEASE_TESTS }} validate

      - name: Clean up
        run: rm -f ~/.terraformrc terraform-provider-github

  goreleaser:
    name: GoReleaser
    needs: [pre-release-tests] # runs only if pre-release tests pass
    runs-on: ubuntu-latest
    # Releases need permissions to read and write the repository contents.
    # GitHub considers creating releases and uploading assets as writing contents.
    permissions:
      contents: write
    environment:
      name: release
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          # Allow goreleaser to access older tag information.
          fetch-depth: 0

      - name: Set-up Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version-file: go.mod
          cache: true

      - name: Install Syft
        uses: anchore/sbom-action/download-syft@fbfd9c6c189226748411491745178e0c2017392d # v0.20.10

      - name: Install Cosign
        uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad # v4.0.0

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@e89d40939c28e39f97cf32126055eeae86ba74ec # v6.3.0
        id: import_gpg
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # v6.4.0
        id: goreleaser
        env:
          # GitHub sets the GITHUB_TOKEN secret automatically.
          GITHUB_TOKEN: ${{ github.token }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
        with:
          args: release --clean

      - name: Attest artifacts
        uses: actions/attest-build-provenance@977bb373ede98d70efdf65b84cb5f73e068dcc2a # v3.0.0
        with:
          subject-checksums: ./dist/${{ github.event.repository.name }}_${{ fromJSON(steps.goreleaser.outputs.metadata).version }}_SHA256SUMS
