name: Close stale issues and PRs
on:
  workflow_dispatch:
  schedule:
    #         ┌───────────── minute (0 - 59)
    #         │ ┌───────────── hour (0 - 23)
    #         │ │ ┌───────────── day of the month (1 - 31)
    #         │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #         │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #         * * * * *
    - cron:  '0 0 * * 3'  
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@5f858e3efba33a5ca4407a664cc011ad407f2008 # v10.1.0
        with:
          stale-issue-message: >
            👋 Hey Friends, this issue has been automatically marked as `stale` because it has no recent activity.
            It will be closed if no further activity occurs.
            Please add the `Status: Pinned` label if you feel that this issue needs to remain open/active.
            Thank you for your contributions and help in keeping things tidy!
          stale-pr-message: >
            👋 Hey Friends, this pull request has been automatically marked as `stale` because it has no recent activity.
            It will be closed if no further activity occurs.
            Please add the `Status: Pinned` label if you feel that this issue needs to remain open/active.
            Thank you for your contributions and help in keeping things tidy!
          days-before-stale: 270
          days-before-close: 7
          exempt-issue-labels: 'Status: Pinned'
          exempt-pr-labels: 'Status: Pinned'
          operations-per-run: 100
          stale-issue-label: 'Status: Stale'
          stale-pr-label: 'Status: Stale'
